include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

linter:
  rules:
  - prefer_single_quotes
  - always_declare_return_types
  - public_member_api_docs
  - always_put_control_body_on_new_line
  - await_only_futures
  - cascade_invocations
  - combinators_ordering
  - flutter_style_todos
  - library_annotations
  - lines_longer_than_80_chars
  - missing_whitespace_between_adjacent_strings
  - prefer_foreach
  - unawaited_futures
  - unnecessary_breaks
  - unnecessary_lambdas
  - unnecessary_parenthesis
  - use_enums
  - sort_pub_dependencies